version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.15.2
    ports:
      - "8080:8080"  # Expose Weaviate on port 8080
      - "50051:50051"  # gRPC port
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true  # Enable anonymous access
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate/data  # Set data persistence path
      - ENABLE_MODULES=text2vec-contextionary
      - DEFAULT_VECTORIZER_MODULE=text2vec-contextionary
      - CONTEXTIONARY_URL=contextionary:9999  # Remove the http:// prefix
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    depends_on:
      - contextionary

  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.0.0
    ports:
      - "9999:9999"
    restart: unless-stopped

volumes:
  weaviate_data:
